services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portofolio-server
    restart: unless-stopped
    env_file: .env.local
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - portofolio_net

networks:
  portofolio_net:
    external: true
